### ISSUE TITLE
theme doesn't work as expected

### ISSUE THREAD

**Issue by leonmax** [oh-my-fish/plugin-theme#1]
First, autocomplete, in addition to themes, also shows all the local files, which in my opinion makes the output cluttered.

```
➜ ~/.oh-my-fish(master) theme 
CONTRIBUTING.md  functions/       plugins/                          script/     themes/
custom/          LICENSE          README.md                         spec/       tools/
Dockerfile       oh-my-fish.fish  robbyrussell  (Oh-my-fish theme)  templates/
```

When trying a theme, here is what it shows instead:

``` fish
➜ ~/.o/themes(master) theme ocean
`ocean` is not a theme.
robbyrussell*
```

Looks like I still have to manually install it first, well, fine, here I change `Theme "ocean"` in the `~/.config/fish/config.fish`, and omf install

```
➜ ~/.oh-my-fish(master) omf install ocean
All packages were already installed.
```

Bummer, I have to reload fish or open another session, so here I reloaded it:

``` fish
➜ ~/.oh-my-fish(master) . ~/.config/fish/config.fish
$fish_plugins usage has been deprecated. Please see https://asciinema.org/a/20802.
$fish_theme usage has been deprecated. Please see https://asciinema.org/a/20802.
fish: Unknown command 'Theme'
~/.config/fish/config.fish (line 12): Theme 'ocean'
                                      ^
from sourcing file ~/.config/fish/config.fish
    called on line 151 of file /usr/local/Cellar/fish/2.2.0/share/fish/config.fish

in function '.'
    called on standard input
```

WTH? I've installed the new oh-my-fish and I am positive about it! How come it's still complaining the incompatibilities? When open in another session, it works (to `omf install`). Did I miss anything?

More importantly, how can I easily test those themes (like advertised) without having to change config.fish and reload again and again?

Thanks in advance for the help.

**Comment by bpinto** [comment]
It used to be possible to change themes using `theme`, but recently we did a change that broke it.
It would be nice if you could work on a solution for this and submit a PR.

**Comment by leonmax** [comment]
I see, I was trying the new changes and I really like it. Thanks for the great work!

I am not really good at shell scripting and I am pretty busy at the moment. I'll check-in later and possibly learn to help if you still need it by then.

Really appreciate your work, OMF rocks!

**Comment by bpinto** [comment]
Thanks for the kind words!

**Comment by chrisdotcode** [comment]
Yes, it seems the `try` command displayed in the gif in the README doesn't exist (anymore?).

I'm willing to PR if you can point me in the right direction.

**Comment by bpinto** [comment]
Sure thing! First `try` command was renamed to `theme`. So you can find the plugin named theme [here](https://github.com/oh-my-fish/plugin-theme). That's where the PR should go to.

The changes are: To get the list of themes we need to do a search similar to this: (https://github.com/oh-my-fish/?utf8=✓&query=theme-), I'm sure we can do a curl/wget to get this list. With this result, we have all the theme names on the catalog.

Once we have it, we just need to download the theme (there is already a omf command to do this) and then set it as the main theme. :D

**Comment by donm** [comment]
The pull request I submitted addresses some of the points here and I think restores the previous functionality.  It doesn't autocomplete themes that aren't downloaded because maybe those themes are _intentionally_ missing in which case the user wouldn't want them to be shown as autocomplete options.  But there is a new command to fetch all availble themes from github.

**Comment by bpinto** [comment]
The PR is really good, thanks @ohspite! We can open another issue in case something is missing.
